projectname: helloworld
jenkins:
  pipeline_project: jenkins-test-2
git:
  repo: https://github.com/ramius345/hello-world-springboot
  ref: jenkins_pipeline
imagestream:
  name: java:8
  namespace: openshift
