kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "{{ .Values.projectname }}.pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: {{ .Values.git.repo }}
      {{- if hasKey .Values.git "ref" }}
      ref: {{ .Values.git.ref }}
      {{- end }}
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  triggers:
  - github:
      secret: 2jFfx2tOrqd9guzUkF_1
    type: GitHub
  - generic:
      secret: jAZeGe-OshQ9qpI7auyx
    type: Generic
  - type: ConfigChange

