apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: jenkins-agent-appdev
  name: jenkins-agent-appdev
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: jenkins-agent-appdev:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: "FROM quay.io/openshift/origin-jenkins-agent-maven:4.1.0\n\n   USER
      root\n\n   RUN curl https://copr.fedorainfracloud.org/coprs/alsadi/dumb-init/repo/epel-7/alsadi-dumb-init-epel-7.repo
      -o /etc/yum.repos.d/alsadi-dumb-init-epel-7.repo && \\ \n\n   curl https://raw.githubusercontent.com/cloudrouter/centos-repo/master/CentOS-Base.repo
      -o /etc/yum.repos.d/CentOS-Base.repo && \\ \n\n   curl http://mirror.centos.org/centos-7/7/os/x86_64/RPM-GPG-KEY-CentOS-7
      -o /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && \\ \n\n   DISABLES=\"--disablerepo=rhel-server-extras
      --disablerepo=rhel-server --disablerepo=rhel-fast-datapath --disablerepo=rhel-server-optional
      --disablerepo=rhel-server-ose --disablerepo=rhel-server-rhscl\" && \\ \n\n   yum
      $DISABLES -y --setopt=tsflags=nodocs install skopeo && yum clean all\n\n   USER
      1001"
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: origin-jenkins-agent-maven:4.1.0
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 2jFfx2tOrqd9guzUkF_1
    type: GitHub
  - generic:
      secret: jAZeGe-OshQ9qpI7auyx
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: quay.io/openshift/origin-jenkins-agent-maven@sha256:0ee1816d40411a94c0dada5eff64824a4edd069af57dc9bfd5
    type: ImageChange
      

