apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.projectname }}-dev
  name: {{ .Values.projectname }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.projectname }}-tls
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deploymentconfig: {{ .Values.projectname }}
  sessionAffinity: None
  type: ClusterIP

