apiVersion: v1
kind: ConfigMap
metadata:
  labels: 
    app: {{ .Values.projectname }}-dev
  name: {{ .Values.projectname }}-tls-cabundle
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
