apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.projectname }}-dev
  name: {{ .Values.projectname }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.projectname }}:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: {{ .Values.git.ref }}
      uri: {{ .Values.git.repo }}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.imagestream.name }}
        namespace: {{ .Values.imagestream.namespace }}
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: xmfdavY0kAifpe5wQg7E
    type: GitHub
  - generic:
      secret: A6EltsAVwJF5HB2mR6Ta
    type: Generic
  - type: ConfigChange

