apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.projectname }}-httpd-dev
  name: {{ .Values.projectname }}-httpd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.projectname }}-httpd:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM httpd:latest
      RUN /usr/bin/mkdir -p /opt/app-root/src
      RUN /usr/bin/curl http://nexus.nexus.svc.cluster.local:8081/repository/demo/test.txt -o /opt/app-root/src/test.txt
      ENTRYPOINT ["/usr/bin/scl", "enable", "httpd24", "--", "/opt/rh/httpd24/root/usr/sbin/httpd" ]
      CMD ["-D","FOREGROUND","-f","/etc/httpd/customconf/httpd.conf"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:latest
        namespace: openshift
    type: Dockerfile
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secret: A6EltsAVwJF5HB2mR6Ta
    type: Generic
  - type: ConfigChange

