apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ssl-init-bc
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ssl-init-bc:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM registry.access.redhat.com/ubi7/ubi:latest
      RUN /usr/bin/yum install -y openssl java-1.8.0-openjdk-headless
      CMD ["/bin/bash","-c", "'openssl pkcs12 -export -out /etc/pki/tls/cert.pkcs12 -inkey /etc/pki/tls.key -in /etc/pki/tls.crt  -certfile /etc/pki/cacerts/service-ca.crt -passout pass:changeit && /usr/bin/keytool -importkeystore -srckeystore cert.pkcs12 -srcstoretype pkcs12 -destkeystore /etc/pki/tls/cert.jks -srcstorepass changeit -deststorepass changeit  '" ]
    type: Dockerfile
  strategy:
    dockerStrategy: {}
    type: Dockerfile
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secret: A6EltsAVwJF5HB2mR6Ta
    type: Generic
  - type: ConfigChange

